Iter4
fyR27/URL-shortening-service pull request #6
Opened 2024-09-05 04:04 UTC by fyR27

Добаваить возможность конфигурировать сервис с помощью аргументов командной строки.
Создать конфигурацию или переменные для запуска со следующими флагами:
Флаг -a отвечает за адрес запуска HTTP-сервера (значение может быть таким: localhost:8888).
Флаг -b отвечает за базовый адрес результирующего сокращённого URL (значение: адрес сервера перед коротким URL, например http://localhost:8000/qsd54gFg).

2024-09-10 19:15 UTC, alkurbatov requested changes
Нужно доработать логику работы с базовым урлом и добавить тесты.

2024-09-24 18:58 UTC, alkurbatov requested changes
Спасибо! Стало намного лучше по сравнению с прошлой итерацией.  
Из серьезных проблем нужно добить парсинг урлов, все остальное хорошо.

2024-09-24 18:58 UTC, alkurbatov commented on .github/workflows/statictest.yml
> +        uses: robinraju/release-downloader@v1.10
question: А почему версия релизного бинаря была понижена?

2024-09-24 18:58 UTC, alkurbatov commented on internal/app/handler.go
> +		parsedBody := store.AddNewURL(body, c)
suggestion: Чуть лучше будет передать конфиг не в handler,  в `app.NewStore(c)`. Тогда store имеет к нему прямой доступ и его не нужно указывать везде в качестве параметра. Это намного удобнее.

2024-09-24 18:58 UTC, alkurbatov commented on internal/app/storage.go
> +	if c.URL[len(c.URL)-1] >= 48 && c.URL[len(c.URL)-1] <= 57 {
style:
1. validURL никем снаружи не используется, а значит его смело можно сделать приватным (то есть с маленькой буквы назвать).
2. Старайся делать ранний выход из функций. Код в итоге получается немного проще и короче, например:
```go
func ValidURL(c *config.Config) string {
    if c.URL[len(c.URL)-1] >= 48 && c.URL[len(c.URL)-1] <= 57 {
        return c.URL + "/"
    }

    return c.URL + c.Host + "/"
}
```
3. Так называемые "волшебные" константы лучше выносить из функции и называть как-то понятно. например:
```go
const baseURLMaxLen = 57
```
Это повышает читаемость кода и потом будет проще почему вообще 57.

2024-09-24 18:58 UTC, alkurbatov commented on internal/app/storage.go
> +	} else {
issue: Если я правильно понимаю, вот эти 48 и 57 - это лимиты, в которые должен base URL поместиться. К сожалению, там может быть гораздо длиннее начало (если не ошибаюсь, в районе 255 символов). Тут надо что-то более умное использовать, если ты хочешь так парсить.

Например, посплитить строку на части и посмотреть что там нашлось, или проверить относительно регулярного выражения. Как вариант - найти готовую либу, которая умеет парсить (они точно есть).

2024-09-24 18:58 UTC, alkurbatov commented on internal/app/handler_test.go
> +			fmt.Println(handler)
nitpick: Отладочная печать осталась.

2024-09-26 14:38 UTC, fyR27 commented on internal/app/storage.go
> +	} else {
Я тут скорее делаю проверку последнего элемента в `url` , проверяю, что если в нем число, значит что это `url` с хостом который можно сразу использовать. Думал еще над тем чтобы проверять последние 4 символа, к примеру, в url'e и если все из них числа то использовать его? Что думаешь по этому поводу?

2024-09-26 14:42 UTC, fyR27 commented on internal/app/handler.go
> +		parsedBody := store.AddNewURL(body, c)
Как я понимаю создать переменную внутри пакета Store, которая будет в себе хранить `URL` ответа?

2024-09-28 11:48 UTC, alkurbatov commented on internal/app/handler.go
> +		parsedBody := store.AddNewURL(body, c)
Нет, не в пакете. Примерно в таком ключе:

```go
type Store struct {
    baseURL string
}

func New(baseURL string) *Store {
    return &Store{baseURL}
}
```

Ну и далее уже ее использовать. Заводить глобальные переменные на уровне пакета старайся в последнюю очередь, это чаще влечет очень разные проблемы особенно в тестах.

2024-09-28 11:59 UTC, alkurbatov commented on internal/app/storage.go
> +	} else {
Ну скажем так: с точки зрения задания можно и последние 4 символа, с точки зрения реального мира там может быть такой вот урл https://my-servcer.com:8888/redirects, который вполне себе валидный.

Я бы предложил тут сильно не заморачиваться, но в целях обучения попробовать сделать проверки через регулярные выражения. В Go они работают не очень быстро, но решают те задачи, которые ты описываешь:

https://zetcode.com/golang/regex/
https://github.com/google/re2/wiki/Syntax

2024-10-01 19:37 UTC, alkurbatov commented on internal/app/storage.go
> +	url, _ := regexp.MatchString("[1-9]", c.URL[len(c.URL)-4:len(c.URL)])
note: Ну ты тут прям совсем скроил) Немного лучше делать в таком ключе (очень приблизительный регэксп, может не работать, скорее для понимания идея):

`"http(s)?([a-zA-Z0-9]+):([0-9]+)"`
Если он пройдет, то в первой группе окажется хост урла, а во второй - порт.

2024-10-01 19:37 UTC, alkurbatov commented on internal/app/storage.go
> +	url, _ := regexp.MatchString("[1-9]", c.URL[len(c.URL)-4:len(c.URL)])
Ну и обрати внимание: 1-9 не включает 0.

2024-10-01 19:39 UTC, alkurbatov commented on internal/app/storage.go
> +	if url == bool(true) {
nitpick: Как-то очень хитро, это же просто bool, значит можно вот так:

```go
matched, _ := regexp.MatchString(...)
if matched {
    //...
}
```

2024-10-01 19:42 UTC, alkurbatov commented on internal/app/storage.go
> +		return c.URL + "/"
issue: Обрати внимание, что парсинг будет работать неправильно, если в регэкспе будет ошибка (см. пример такой ситуации тут https://pkg.go.dev/regexp#example-MatchString).  

Чтобы ошибку не проверять и о проблемах с регуляркой узнавать как можно раньше, нужно использовать заранее предсозданный объект регэкспа и его методы.
https://pkg.go.dev/regexp#example-Regexp.MatchString

Объект можно сделать глобальным.

2024-10-01 19:43 UTC, alkurbatov requested changes
Нужно поправить логику работы с регуляркой, остальное хорошо.

2024-10-03 07:16 UTC, alkurbatov approved these changes
Спасибо! Стало лучше.

2024-10-03 07:16 UTC, alkurbatov commented on internal/app/storage.go
> +	if url == bool(true) {
Все еще актуально.

2024-10-09 14:42 UTC, merged